name: Run Music Bot 2

on:
  workflow_dispatch:
  schedule:
    - cron: "55 */5 * * *"

concurrency:
  group: music-bot-2
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_2 }}
      BOT_NODE_INDEX: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Lavalink
        run: wget https://github.com/lavalink-devs/Lavalink/releases/download/4.0.8/Lavalink.jar

      - name: Start Lavalink
        run: java -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -jar Lavalink.jar &

      - name: Wait for Lavalink
        run: sleep 10

      - name: Start Bot
        run: node --max-old-space-size=1024 bot.js
